#!/usr/bin/env bash
# Install and configure HAproxy on your lb-01 server.

# Update the system
sudo apt-get -y update
apt-get -y install haproxy

# Config the load balncer to user roundrobin
server_config=\
"
frontend  ehoneah-frontend
        bind *:80
        mode http
        default_backend ehoneah-backend
backend ehoneah-backend
        balance roundrobin
        server 63210-web-01 54.210.152.224:80 check
        server 63210-web-02 18.206.208.23:80 check
"
echo "$server_config" | sudo tee -a /etc/haproxy/haproxy.cfg

# enable haproxy to be started by init script

echo "ENABLED=1" | sudo tee -a /etc/default/haproxy

sudo service haproxy restart
