#!/usr/bin/env bash
# Manange a background precess

if [ ! $# -eq 1 ]
then
	echo "Usage: manage_my_process {start|stop|restart}"
fi

if [ "$1" = "start" ]
then
	./manage_my_process &
	echo "$!" | sudo tee /var/run/my_process.pid > /dev/null
	echo "manage_my_process started"

elif [ "$1" = "stop" ]
then
	sudo kill "$(sudo cat /var/run/my_process.pid)"
	sudo rm /var/run/my_process.pid
	echo "manage_my_process stopped"

elif [ "$1" = "restart" ]
then
	sudo kill "$(sudo cat /var/run/my_process.pid)"
	sudo rm /var/run/my_process.pid
	sudo ./manage_my_process &
	echo "$!" | sudo tee /var/run/my_process.pid > /dev/null
	echo "manage_my_process restarted"
fi
