#!/usr/bin/env bash
#scrip that is displaying "Best chool" 10 time using while

count=0

while [ $count -lt 10 ]
do
    echo "Best School"
    if [ "$i" = 8 ]
    then
        echo "good luck"
    fi
    (( count++ ))
done
