#!/usr/bin/env bash
#scrip that is displaying "Best chool" 10 time using while

count=0
while [ $count -lt 10 ]
do
    if [ "$count" = 4 ]
    then
        echo "bad luck"
    elif [ "$count" = 8 ]
    then
        echo "good luck"
    else
        echo "Best School"
    fi
    (( count++ ))
done
