#!/usr/bin/env bash
# Time is money

hours=0
minutes=1
while [ "$hours" -lt 13 ]; do
        while [ "$minutes" -lt 60 ]; do
                if [ "$minutes" = 1 ]
                then
                        echo "Hour: $hours"
                fi
                echo "$minutes"
                (( minutes++ ))
        done
        (( minutes = 1 ))
        (( hours++ ))
done