#!/usr/bin/env bash
# Bash script that configures an Ubuntu server with the below requirements

cd | cp /etc/hosts ~/hosts.new
cd | echo "127.0.0.2 localhost" > ~/hosts.new
cd | echo "8.8.8.8 facebook.com" > ~/hosts.new
cd | cp -f ~/hosts.new /etc/hosts
