#!/usr/bin/env bash
# Create the peer public/private key using ksa algorithm
# passphrase will be betty
# The private key will be named school
# Number of bits ti generate is 4096

ssh-keygen -b 4096 -N betty -f school